### ISSUE TITLE
Design demos for website

### ISSUE THREAD

**Issue by chaixinzhe2000** [FullStackAtBrownTeam/project-pre-law-society#2]
### TODO
Please browse websites with different features and design languages. Post 3 websites that you like the best (design-wise), and explain how we can adopt its design for Brown Pre-Law Society website.

Good way to find website demos: 
[https://themeforest.net/category/wordpress](ThemeForest)
[https://www.squarespace.com/templates](Squarespace)

**Comment by dustin-wu** [comment]
https://www.uber.com: I like how they implemented the “Company” dropdown in the navbar; the “Company” button itself does not link to any page but rather serves as a toggle to show/hide the dropdown, and I think that this is a dropdown implementation that we could use. I also like how the buttons are highlighted when they are hovered over/pressed. I also think that the “About Us” page (accessible under the dropdown) stands out thanks to the several full-width and smaller images that visualize aspects about their mission.

https://calgarydefence.com: I like how the home page is done. The full-width image definitely has some attention-grabbing prowess. Below the image are some areas that link to other pages of the website. I like how these are compact so as not to be redundant and how well-integrated they are into the home page. I also like how, in the “Lawyers” page, the lawyers are listed in a grid of cards. The contact page is also really polished, with transparent elements and an integrated captcha, which I think would be more aesthetically pleasing but perhaps less useful than an integrated google form. Finally, I like the colors used for most of the background and text, it’s easy on the eyes and more unique than simple black on white. I think that we should experiment with combinations of lighter and darker colors for the background and text of the website, respectively.

https://harbor-demo.squarespace.com : The homepage on this website also makes good use of a full-width image and I like how the images “fade in” as you scroll down, perhaps this is something that we can do to make the website pop. The sections that link to other areas of the site are differentiated with a different colored background, which is something that we could try out. Finally, I like how the home page uses a combination of left-aligned larger text to list out the features ("A market place of...", "Workshops & Events", etc) of the fair with right-aligned smaller text to describe those features. This is also something that we could try incorporating.

**Comment by linus-sun** [comment]
https://zoom.us/
-i like how the navbar indicates which categories dropdown with a triangle; theoretically, if we had some categories that we didn't want to use a dropdown for on the navbar (e.g. the "join us" category simply links to a google form) we could use this
-at the top of the page, the main image has left and right arrows which change the background image; we could take this a step further and change text as well (so you could click on the left and right arrows to change what section of the website to be displayed.)
-even with the left and right arrows, you can continue to scroll down to look through different elements (in zoom's case, reasons to use the software, their partners, and their features); we could display non-redundant elements under the main changeable image as well

https://nolan-demo.squarespace.com/
-client requested a grayscale/black+white color palette, possible example of a black+white color palette that could work
-subtler colors allow the images on the front page to stand out more in contrast; however, if we don't have a lot of media we want to emphasize then maybe a more subdued color palette is not necessary here
-very simple footer at the bottom; given that we likely won't need to place too much in the footer i like the simplicity + left-alignment of the footer links

https://www.chess.com/
-the dark mode ui showcases another example of a grayscale color palette that lets the media images stand out more
-a sidebar instead of a top navbar could be something we experiment with, instead of dropdown the sidebar would expand out into another list of subcategories
-scrolling down, the activity tab showcases a potential way to format the pre-law society events as a top-down list of chronological events you can scroll down through
-the way different elements are placed in boxes makes each one distinct

**Comment by coberg19** [comment]
https://www.eventbrite.com/
I like how this displays events in cards. Each card displays all important information about the event without being too cluttered (photo, name of event, and time), and when you click on each event it takes you too a page with more information. I think we can incorporate the idea of having each event listed individually and then have them link to a page with more information about the event. 

https://www.outreach.io/company?utm_source=saaswebsites.com

I really liked the home page of this website. I liked how the first thing you see is an image and a line about what the company can do for you. I liked the design of the nav bar and how every drop-down menu item has an icon next to it. I also liked the structure of their events page, it has events separated by past and upcoming and each event is presented in a card that links to the event page. I also liked the about us page. They display everyone on their board in circular photos with their name underneath and then you click on that person it expands into a box with more information about them.

https://www.medallia.com/

I like how the overall design of this website is simple and clean. This website also has a nice events page where all the events are displayed in a list and you can click on the side for more details. I think this could be a good way to display events in a chronological order. I also thought that the resources section of this website was really nice and I liked how it categorized each different resource (ebook, brochure, etc.). 

https://orkestra.ca/en/team-and-careers
This one is not really practical at all, I just found it when I was looking for inspiration and thought they had a really cool about us page and wanted to share lol.

**Comment by chaixinzhe2000** [comment]
good job!
