### ISSUE TITLE
Good Website Design

### ISSUE THREAD

**Issue by chaixinzhe2000** [FullStackAtBrownTeam/project-pre-law-society#3]
### Action Item
Similar to last time, I want everyone to find **websites** with the good design language and provide a short explanation for each one. Just make sure you do the sections that were assigned to you!

**Deadline: Before Saturday Meeting**

### What do I mean by "design language"?
A real "design language" is usually a set of stylistic guideline that is published by companies, such as:

[Human Interface Guideline by Apple](https://developer.apple.com/design/human-interface-guidelines/)
[Fluent Design by Microsoft](https://www.microsoft.com/design/fluent/#/)

However, we are making websites, and we don't have enough time to develop a full design language. Therefore, what we want to do is to find some good websites, and learn from their designs. 

### Example
_[Github Universe](https://githubuniverse.com/)_
_I love Github Universe's box design for displaying events. Maybe we can also incorporate it into our own website. Also, neon light is really a good color scheme for dark websites._

### How to find a good website for the task?
One way is to find a big company's annual conference page. Of course, make sure their design fit our need (we don't need crazy animation transition that Apple might have).

**Good luck, and looking forward to your reply!**

**Comment by dustin-wu** [comment]
**Navbar/Footer:** 
https://lne-gmed.com 
Navbar: I like how the drop-down automatically reveals itself when you hover over a link. The scroll-over effect of changing the text color and underlining the text is simple and effective, and the company logo on the top-left corner shrinking when you scroll down to become less intrusive is a smart feature.

Footer: The column-style footer on this website is minimalistic but gets the job done; having small lines in between the title and the links of each column is a nice touch, as is the slight color transition from white to light grey and the positioning of the social links.

https://biocycle.fr
Navbar: This header uses dropdown that toggle when clicked, which is another alternative to the previous website that might work better. Having logos next to each of the drop-down items is a nice touch. This website also pulls off the “blended-in” navbar with the same color as the background nicely; it might be because there is a light green banner effect right below. In addition, the contact link is made into an emphasized button which gives some color to the navbar and I think that we could do that to our events link. Finally, I noticed that this navbar vanishes when you scroll down; this is something that we could consider but would probably make the website harder to navigate.

Footer: This website also has a really neat and organized column-style footer. However, most of the footer is dedicated to a newsletter link which might not be needed in our website’s case. Regardless, I think that the logo being placed to the side of the footer works well.
 
https://experience.dropbox.com 
Navbar: Dropbox’s navbar is very minimalistic, with dropdown menus appearing as you hover over the links. I think that the separated navbar is something that might work better for our website, although I’m not sure what’s up with the black navbar right below the white one.

Footer: The footer on this website is as bare-bones as it gets, and if we wanted to go with this kind of minimalistic aesthetic we cold replace the first one or two columns with a logo and the “connect” column with the typical social media circles.

https://jeckra.com.au 
Navbar: The navbar is another example of something simple that gets the job done. The logo placed on the opposite side of the navbar links creates a clean separation.

Footer: The black footer is similar to what we mocked-up in the wireframe and I think that everything is positioned in a balanced manner. I could see a logo being placed to the left of the text on the left.

**Banner:**
https://buildyourfuture.withgoogle.com/events/ 
Google is known for having minimal website design and this events banner is no different. The offset image with the yellow hexagon is incredibly simply but I think that it works really well. The left part with three different sizes of text and a distinguished button is also well-organized.

https://www.eventbrite.com/d/online/events/
I like how the second events banner is done, with the image being placed in between a blurred background gradient and a description and link to more events.

**About The Club:**
https://www.nikolaibain.com/about 
I like how the top section is sectioned off with a light grey and how the header of the about statement is bolded. The image to the left is a nice touch, but I’m not sure if having an image in this section is something that we’d want.

https://www.audible.com/about/ 
Similar to the previous website, this one has a bolded header and has an image to the left. I think that the small orange line between the header and the description is a nice touch.

**Comment by coberg19** [comment]
**Join us / contact us:** 

https://bff.co/contact/
I like how the contact us page is simple and straightforward. I'm not sure if we will have more than one email or contact form, but I like how they structured the different emails in boxes. We could use a similar design by having the contact email in one and links to social media in another. 

http://www.letstravelsomewhere.com/contact/#
I like the structure of this contact us page where they have a blurb about contacting then a link to contact and then a series of links to social media on the right. We could incorporate a similar structure of having a button/link to the email/google form and links to social on the right.

https://infinum.com/contact
I like how this design is simple and easy to navigate. We could do something similar to this with join us and contact us buttons linking to the different google forms. 

**Resources:** 
https://www.submittable.com/resources/?utm_source=saaswebsites.com
I like how they displayed each resource in a card and indicated different sections by changing colors. I'm not sure if this would work well with our website design if the resources page is just meant to be a series of links?

https://www.cultureamp.com/events/virtual-events/?utm_source=saaswebsites.com
https://www.medallia.com/resource-library/?utm_source=saaswebsites.com
Similar to the example above I like how both of these resources pages are organized and how each type of resource has a different colored header. Again, I'm not sure if this would be the best display given the types of resources we will have.

https://www.wealthsimple.com/en-ca/learn/?utm_source=saaswebsites.com
I like how it has the category on the first slide and then scroll for other the resources in that category. 

https://support.google.com/youtube/?hl=en-GB#topic=9257498
Another option for the resources page could be to do something similar to this FAQ where we have each resource linked under the research category in a drop down. I like this design because it is clean and easy to use. 

**Banner** 

https://www.patreon.com/?utm_source=saaswebsites.com
I like the contrasting colors and negative space. I think that we could incorporate this design into the pre-law website by having text on one side and a photo on the other. 

https://www.cultureamp.com/?utm_source=saaswebsites.com
I like how this banner doesn't take up the entire height of the screen and has a simple design that isn't too distracting.

**Stay in touch**
https://bff.co/contact/

I like the simplistic design of the stay in touch in the footer. I think it's straightforward and easy to use.

**Comment by linus-sun** [comment]
**Banner**
https://company.vice.com/about/
-eye catching image, full width
-i like how the drop down is integrated into the banner
https://www.gravelinstitute.org/
-pretty simple, concise
-i like the little interactivity of the image element on the right?
https://www.twitch.tv/p/en/company/
-text pops in, catches your attention
-i don’t really like the random images interspersed through however
-also bigger than the screen so it makes you want to keep scrolling down intuitively, pluses/minuses

**Mission**
https://www.nytco.com/company/
-very simple and barebones, conveys info well
-powerful image that draws you into the center element
https://company.vice.com/about/
-i like how the different text scrolls through and focuses on different pieces of information

**Leadership Banner**
http://youngart.us/#Artists
-looks similar to the design we have on figma
-would likely replace links to different social media with text blurbs
-background image isn’t too distracting but also looks nice
https://medium.com/about?autoplay=1
-different design with icon next to name
-we could make icons larger if we want more attention on images
-could also add blurbs underneath the names
https://www.uber.com/newsroom/leadership/
-also looks similar to the design we have on figma
-instead of redirecting name to different page, could just have popup section

**Leadership Full**
https://www.nytco.com/company/people/
-rectangular images, similar to ideas we’ve discussed on figma
-i like how the full view comes in from the side
https://www.uber.com/newsroom/leadership/
-on the full page, we could have multiple sections that you could scroll down through
-very simple, clean design

**FAQ**
https://www.microsoft.com/en-gb/software-download/faq
-different sections for different topics
-i like how hover highlights the question you’re on
-simple, intuitive
https://melodics.com/support#faq-header
-has a sidebar that allows you to skip to different sections of the FAQ
-again, hover highlights the question and moves the text to catch your eye
-questions have a link button that allow you to copy a redirect to the specific question, might be useful if we anticipate people sending faq questions to others

**Comment by chaixinzhe2000** [comment]
good job everyone, closing the issue.
